### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by clehner**
- Fixed some errors.
- Added a `errors` tab to show new errors. Is this too developer-centric?

### CODE REVIEW

**Comment by dominictarr** [comment]
hmm. as a developer, I think I'd prefer to get errors in the dev tools?
does this interfeer with that?

**Comment by clehner** [comment]
It shouldn't interfere with it, no

**Comment by dominictarr** [comment]
okay so ev.preventDefault() means that errors arn't in the console anymore. can we remove that?

**Comment by clehner** [comment]
yes, i think it's safe to remove that. sorry, i tried throwing an error in a timeout and it showed up in the console so i assumed it was fine.

**Comment by dominictarr** [comment]
I removed this at some point, but this still completely swallows errors in firefox

**Pull request merged**
