### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by clehner**
Would we like to see some kind of notifications in Patchbay of mentions and things related to the current uxer?

Possible implementation approach: factor out notifications from ssb-notifier and add a patchbay tab to show them like a feed. This would not take into account watched threads like in Patchwork.

### CODE REVIEW

**Comment by clehner** [comment]
Attached a commit adding a notifications tab. It is very basic, it just filters messages from the log based on whether they have something to do with the current user. It doesn't use code shared with ssb-notifier but it uses similar logic to detect mentions, follows, digs, and replies. For now it just renders the messages as-is, not giving more detailed descriptions of their relevance to the user.

**Comment by dominictarr** [comment]
merged into 1.6.0

**Comment by dominictarr** [comment]
This is a good start. I'd like to be able to separate things I will react to like replies and mentions from things that are merely informational, like likes.

**Comment by clehner** [comment]
>  I'd like to be able to separate things I will react to like replies and mentions from things that are merely informational, like likes.

That makes sense. I was thinking similarly about likes taking up a lot of space in the public feed.

Some ideas:
- hide likes from notifications
- put likes of your stuff into a separate tab
- decrease the size and/or visual prominence of likes (and follows). i.e. make them fit on one line, without border/bg, with smaller avatar icon
- combine multiple like messages into a single item in the feed

**Comment by dominictarr** [comment]
I was thinking an easy thing to do, while maintaining the streamyness (which is a key part of the architecture) would be to reduce "simple actions" (likes, follows, etc) into a single item.
it would just say "bob yupped X,Y,Z and followed A,B,C" in one line. Ususally you get a bunch of reactions from one person, because they come on, interact with a bunch of stuff, then stop.

**Comment by dominictarr** [comment]
oh, question: does notifications do a full scan? for new users on a lite client we don't want to make that download the whole feed. It should probably stop once it gets to messages earlier than their first message.

**Comment by clehner** [comment]
> does notifications do a full scan?

yes.

> for new users on a lite client we don't want to make that download the whole feed. It should probably stop once it gets to messages earlier than their first message.

agreed. i'll add that

> I was thinking an easy thing to do, while maintaining the streamyness (which is a key part of the architecture) would be to reduce "simple actions" (likes, follows, etc) into a single item.
it would just say "bob yupped X,Y,Z and followed A,B,C" in one line. Ususally you get a bunch of reactions from one person, because they come on, interact with a bunch of stuff, then stop.

that would make sense for `public` and `feed`.

**Pull request merged**
