### PR TITLE
yups to digs, digs to bottom right corner

### PR DESCRIPTION
**Pull request by evbogue**
I changed yups to digs for consistency across the three apps, Patchwork/git-ssb-web/Patchbay. Feel free to reject if yup is preferred. 

In the future perhaps the deployer can set this to 'Star' or 'Yarr' in a config file?

WIP commit. Next I'm going to try to get voting into the bottom right corner of the screen. Next next I'm going to try to get a reply button down there too.

Ok this is mostly accomplished. The one goal I have is to remove the ' | ' when there is no dig button.

### CODE REVIEW

**Comment by evbogue** [comment]
Ok this is mostly accomplished. The one goal I have is to remove the ' | ' when there is no dig button.

**Comment by dominictarr** [comment]
I kinda like yup. but that is why I put the "expression" field on.
http://wx.larpa.net:8989/msg/%ym8xH+z4R9qId5ioPV5jALGM0m2Kp4EPwt6bEM+kQGY=.sha256

I think the _user_ should be able to choose their own expression... because language needs to evolve from the bottom up, from use...

What does the `|` do? does it just mark the end of the actions?

**Comment by evbogue** [comment]
The | (pipe) was simply a symbol between Dig/Yup and Reply. It seemed to balance it out a bit visually.

"Dig | Reply"

Bottom-up expressions seems to be a good idea. Also it'd allow for drop-downs and such.

**Comment by evbogue** [comment]
I don't particularly love 'Dig' either, as it reminds of the Digg days and also seems to be 1960's hippy slang. It only seemed to me that people might have been confused about what a Yup is.

**Pull request merged**
