### PR TITLE
Right align message metadata

### PR DESCRIPTION
**Pull request by dominictarr**
I think this looks better.
screenshot_right-align-meta

i think the next thing is the ID input is ugly. That could be a "copy id" option like patchwork has,
or also there could be a header that appears on the message view (i.e. the thread page) which would have a selectable input box.

### CODE REVIEW

**Comment by dominictarr** [comment]
@evbogue @clehner what do you think?

**Comment by evbogue** [comment]
@dominictarr Looks good to me! 

I agree that the id could be hidden or more beautiful than it is.

**Comment by clehner** [comment]
i like

**Comment by dominictarr** [comment]
merging.

**Comment by dominictarr** [comment]
merged into 1.5.1

**Pull request merged**
